// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rec_be.Data;

#nullable disable

namespace rec_be.Migrations
{
    [DbContext(typeof(RACPostgreSQLDbContext))]
    partial class RACPostgreSQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rec_be.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_date");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_booking");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_booking_room_id");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.Config", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("text")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_value");

                    b.HasKey("ConfigKey")
                        .HasName("pk_config");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdCard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_card");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.HasKey("Id")
                        .HasName("pk_guest");

                    b.ToTable("guest", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.LateCheckOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("Charge")
                        .HasColumnType("numeric")
                        .HasColumnName("charge");

                    b.Property<int>("ExtraHours")
                        .HasColumnType("integer")
                        .HasColumnName("extra_hours");

                    b.HasKey("Id")
                        .HasName("pk_late_check_out");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_late_check_out_booking_id");

                    b.ToTable("late_check_out", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Occupied")
                        .HasColumnType("boolean")
                        .HasColumnName("occupied");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_number");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("room_type_id");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("ix_room_room_type_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.RoomGuest", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer")
                        .HasColumnName("guest_id");

                    b.HasKey("BookingId", "GuestId")
                        .HasName("pk_room_guest");

                    b.HasIndex("GuestId")
                        .HasDatabaseName("ix_room_guest_guest_id");

                    b.ToTable("room_guest", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id")
                        .HasName("pk_room_type");

                    b.ToTable("room_type", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.ServiceContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Avialable")
                        .HasColumnType("boolean")
                        .HasColumnName("avialable");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IDCard")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_card");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_role");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.HasKey("Id")
                        .HasName("pk_service_contacts");

                    b.ToTable("service_contacts", (string)null);
                });

            modelBuilder.Entity("rec_be.Models.Booking", b =>
                {
                    b.HasOne("rec_be.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_room_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("rec_be.Models.LateCheckOut", b =>
                {
                    b.HasOne("rec_be.Models.Booking", "Booking")
                        .WithOne("LateCheckOut")
                        .HasForeignKey("rec_be.Models.LateCheckOut", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_late_check_out_booking_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("rec_be.Models.Room", b =>
                {
                    b.HasOne("rec_be.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_room_types_room_type_id");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("rec_be.Models.RoomGuest", b =>
                {
                    b.HasOne("rec_be.Models.Booking", "Booking")
                        .WithMany("RoomGuests")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_guest_booking_booking_id");

                    b.HasOne("rec_be.Models.Guest", "Guest")
                        .WithMany("RoomGuests")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_guest_guest_guest_id");

                    b.Navigation("Booking");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("rec_be.Models.Booking", b =>
                {
                    b.Navigation("LateCheckOut");

                    b.Navigation("RoomGuests");
                });

            modelBuilder.Entity("rec_be.Models.Guest", b =>
                {
                    b.Navigation("RoomGuests");
                });

            modelBuilder.Entity("rec_be.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("rec_be.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
